server:
  port: 8024 #内嵌的Tomcat 端口号：8024
  address: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://10.100.41.4:3818/TCUSANORDER
    username: TCUSANORDER_test
    password: d1H2msHeD1H4ntIG3A7dGx
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 47.111.253.203
    port: 6379
    password: testmaster123
    database: 0
    # 对应的RedisProperties.Jedis 配置
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1